#!/bin/bash

# stop right away in case of any error
set -e

# we will compile squid as normal user, and NOT as root
if [[ $EUID -eq 0 ]]; then
   echo "This script must NOT be run as root" 1>&2
   exit 1
fi

# modify configure options in debian/rules, add --enable-ssl --enable-ssl-crtd
patch squid3-3.3.8/debian/rules < rules.patch

# modify algorithm to sign the root cert
patch squid3-3.3.8/src/ssl/gadgets.cc < gadgets.cc.sha256.patch

# and also the fix for Firefox inadequate key error
patch squid3-3.3.8/src/ssl/gadgets.cc < gadgets.cc.firefox.patch

# build the package
cd squid3-3.3.8 && dpkg-buildpackage -rfakeroot -b



****************************************************************************************************************
--- rules 2013-11-15 11:49:59.052362467 +0100
+++ rules.new 2013-11-15 11:49:35.412362836 +0100
@@ -19,6 +19,8 @@
DEB_CONFIGURE_EXTRA_FLAGS := --datadir=/usr/share/squid3 \
  --sysconfdir=/etc/squid3 \
  --mandir=/usr/share/man \
+   --enable-ssl \
+   --enable-ssl-crtd \
  --enable-inline \
  --enable-async-io=8 \
  --enable-storeio="ufs,aufs,diskd,rock" \
  **************************************************************************************************************
  
  --- gadgets.cc  2013-07-13 15:25:14.000000000 +0200
+++ gadgets.cc.new      2015-11-09 23:00:47.591124352 +0100
@@ -389,9 +389,9 @@

     /*Now sign the request */
     if (properties.signAlgorithm != Ssl::algSignSelf && properties.signWithPkey.get())
-        ret = X509_sign(cert.get(), properties.signWithPkey.get(), EVP_sha1());
+        ret = X509_sign(cert.get(), properties.signWithPkey.get(), EVP_sha256());
     else //else sign with self key (self signed request)
-        ret = X509_sign(cert.get(), pkey.get(), EVP_sha1());
+        ret = X509_sign(cert.get(), pkey.get(), EVP_sha256());

     if (!ret)
         return false;
*******************************************************************************************************************

--- gadgets.cc  2013-07-13 15:25:14.000000000 +0200
+++ gadgets.cc.new      2015-11-09 22:33:12.179118147 +0100
@@ -257,7 +257,7 @@
 mimicExtensions(Ssl::X509_Pointer & cert, Ssl::X509_Pointer const & mimicCert)
 {
     static int extensions[]= {
-        NID_key_usage,
+        //NID_key_usage,
         NID_ext_key_usage,
         NID_basic_constraints,
         0
*******************************************************************************************************************         
